spring.application.name=autenticacion-servicio
server.port=8090
server.address=0.0.0.0

spring.datasource.url=jdbc:h2:mem:auth_servicio_h2;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

spring.flyway.enabled=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

jwt.secret=FoodFastClaveJWTUltraSegura2026ParaMicroserviciosConMasDe42Caracteres
jwt.expiration=86400000

springdoc.swagger-ui.path=/swagger-ui.html
