services:
  inventario-servicio:
    build: .
    container_name: inventario-servicio
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: mysql-foodfast
      DB_PORT: 3306
      DB_NAME: inventario_db
      DB_USER: root
      DB_PASSWORD: root
      EUREKA_URL: http://eureka-server:8761/eureka/
