services:
  reparto-servicio:
    build: .
    container_name: reparto-servicio
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: mysql-foodfast
      DB_PORT: 3306
      DB_NAME: reparto_db
      DB_USER: root
      DB_PASSWORD: root
      EUREKA_URL: http://eureka-server:8761/eureka/
      JWT_SECRET: FoodFastClaveJWTUltraSegura2026ParaMicroserviciosConMasDe42Caracteres
